-- Drop tables if they exist
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS movies;

-- Create books table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL UNIQUE,
    synopsis TEXT,
    main_ideas TEXT,
    status TEXT DEFAULT 'available',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add the status check constraint
ALTER TABLE books 
  ADD CONSTRAINT IF NOT EXISTS books_status_check 
  CHECK (status IN ('available', 'checked_out', 'reserved', 'maintenance'));

-- Add unique constraints if they don't exist
ALTER TABLE books 
  ADD CONSTRAINT IF NOT EXISTS books_title_key UNIQUE (title);

-- Create movies table
CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL UNIQUE,
    synopsis TEXT,
    genre TEXT,
    release_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add unique constraints if they don't exist
ALTER TABLE movies 
  ADD CONSTRAINT IF NOT EXISTS movies_title_key UNIQUE (title); 